baseURL = 'https://hbbymth42.github.io/hugomath42'
languageCode = 'en-US'
title = 'Sample Site for Hugomath42 Theme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[taxonomies]
project = 'projects'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
