name = 'Hugomath42'
license = 'MIT'
licenselink = 'https://github.com/hbbymth42/hugomath42/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/hbbymth42/hugomath42'

# Taxonomy terms
tags = ['projects']

[author]
  name = 'Hobbymath42'
  homepage = 'https://hbbymth42.github.io'
